### ISSUE TITLE
如何指定自动生成的elegant/routes.ts文件路由的component

### ISSUE THREAD

**Issue by jarryxy** [soybeanjs/elegant-router#10]
如何指定自动生成的elegant/routes.ts文件路由使用的component,比如需要layout.blank$view.403，而每次生成的是layout.base$view.403

**Comment by honghuangdc** [comment]
手动改路由数据

**Comment by honghuangdc** [comment]
已经存在component，下次生成不会覆盖的

**Comment by jarryxy** [comment]
明白了 感谢
