### ISSUE TITLE
无法指定除src/views目录以外的目录生成路由

### ISSUE THREAD

**Issue by saronwei** [soybeanjs/elegant-router#11]
考虑到微前端的能力，每个模块自身都可以独立运行，可能需要将src/views的视图分割到src/modules/views下面，当时目前pagePatterns貌似不支持这项能力，是否可以支持？

**Comment by honghuangdc** [comment]
有个属性 pageDir，指定页面的目录，默认是src/views

**Comment by saronwei** [comment]
好吧 我先试试 麻烦辛苦辛苦 补充一下文档吧

**Comment by honghuangdc** [comment]
https://github.com/soybeanjs/elegant-router/blob/main/README.zh_CN.md#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE

**Comment by saronwei** [comment]
希望pageDir这个属性能够支持诸如：“src/modules/**/views/*.vue” 这种通配符匹配的方式, 现在的pageDir貌似不支持

**Comment by honghuangdc** [comment]
pageDir可以设置为 src/modules，
匹配模式可以通过 pagePatterns 去设置
