### ISSUE TITLE
多参数页面名称应该如何定义

### ISSUE THREAD

**Issue by checkZH** [soybeanjs/elegant-router#14]
[id].vue 可以接收一个参数,且能自动生成相应的router配置
当修改elegant-router.ts 下路由的参数名称和添加参数名称时重启项目修改的部分会被重置
请问如何定义多个参数
例如修改那部分代码可以支持多参数 或者 在哪里可以配置某些路由配置重启项目不被删除(多参数)

**Comment by honghuangdc** [comment]
默认只支持单个路径参数，需要多个路径参数的路由，请使用高级参数路由：https://github.com/soybeanjs/elegant-router/blob/main/README.zh_CN.md#%E9%AB%98%E7%BA%A7%E7%9A%84%E5%8F%82%E6%95%B0%E8%B7%AF%E7%94%B1
