### ISSUE TITLE
您好想问下如何设置动态 meta 属性下的 title

### ISSUE THREAD

**Issue by yyqxjwxy** [soybeanjs/elegant-router#15]
以下是我的 js代码
```js
document.title = XXX
```
这样设置以后本地是可以看到页面标题变化的，但是部署到服务器上在线在手机看并没有正确显示还是显示的路由表里写死的 title

**Comment by yyqxjwxy** [comment]
补充一下，我的 H5 页面内嵌在安卓的 webview里，这个标题是安卓端控制

**Comment by honghuangdc** [comment]
> 以下是我的 js代码
> 
> ```js
> 
> document.title = XXX
> 
> ```
> 
> 这样设置以后本地是可以看到页面标题变化的，但是部署到服务器上在线在手机看并没有正确显示还是显示的路由表里写死的 title

变更标签的文本和该插件没关系

**Comment by honghuangdc** [comment]
> 以下是我的 js代码
> 
> ```js
> 
> document.title = XXX
> 
> ```
> 
> 这样设置以后本地是可以看到页面标题变化的，但是部署到服务器上在线在手机看并没有正确显示还是显示的路由表里写死的 title

如果是自己的项目，得自己排查相关逻辑了

**Comment by honghuangdc** [comment]
> 补充一下，我的 H5 页面内嵌在安卓的 webview里，这个标题是安卓的那边的显示

你这问题的范围我也无能为力
