### ISSUE TITLE
当路由的name与组件name不同时keepAlive无效

### ISSUE THREAD

**Issue by faruzanCN** [soybeanjs/elegant-router#19]
当路由的name与组件name不同时keepAlive无效，之所以出现这种情况是因为需要大量复用组件，但是呢name与path必须有层级对应关系，导致name不能与组件name相同，希望path能脱离与name必须有层级关系，看是否能增加一个属性配置来代替name而与path的对应关系

**Comment by honghuangdc** [comment]
只有当自定义路由复用现有页面的组件时才会出现这种情况，这种只能通过设置被复用的页面路由为缓存组件，也没其他更好方法了。
