### ISSUE TITLE
pagePatterns not working when first time start project

### ISSUE THREAD

**Issue by nguyenhan-se** [soybeanjs/elegant-router#21]
When use pagePatterns can't generate file

**Comment by honghuangdc** [comment]
Give the minimum replication

**Comment by nguyenhan-se** [comment]
you can:
step 1: remove elegant-router.d.ts existing in project
step 2: set pagePatterns: ['**‍/index.vue', '**‍/[[]*[]].vue'] on soybean-admin project
re-run -> related files elegant-router can't re-generate

**Comment by honghuangdc** [comment]
it seems the first time it generate empty routes, if run dev again, it success.

**Comment by nguyenhan-se** [comment]
> it seems the first time it generate empty routes, if run dev again, it success.

nice
can u check pagePatterns: ['**‍/page.vue', '**‍/[[]*[]].vue'], I tried (run dev, restart project, add new file,...) it seems not working

**Comment by honghuangdc** [comment]
The error is due to the use of illegal asterisks, copy the code referencing vite.config.ts inside template-vue

https://github.com/soybeanjs/elegant-router/blob/3d3446d65cdacd63341b801b28269bb89df291a4/examples/template-vue/vite.config.ts#L13
