### ISSUE TITLE
怎么指定二级路由的默认子路由？

### ISSUE THREAD

**Issue by Leeiouy** [soybeanjs/elegant-router#23]
你好，请问如何设置二级路由子页面的默认路由？目前，每次运行项目时，系统会根据 view 文件夹下的文件名按字母顺序生成路由数据。例如，如果我的子页面文件名分别以 A、R、Z 开头，系统会默认将 A 开头的页面文件作为默认子路由。我想指定 Z 开头的页面文件为默认路由，请问该如何实现？

**Comment by honghuangdc** [comment]
用vue-router里面的redirect属性 redirect: { name: '子路由的路由名称' }

**Comment by Leeiouy** [comment]
> 用vue-router里面的redirect属性redirect: { name: '子路由的路由名称' }

非常感谢
