### ISSUE TITLE
关于自定义路由

### ISSUE THREAD

**Issue by zuihou** [soybeanjs/elegant-router#24]
1. 修改 customRoutes
<img width="1388" alt="image" src="https://github.com/soybeanjs/elegant-router/assets/8500410/7e9347bf-bf58-46e7-a594-5a2e6960bed6">

2.手动修改elegant-router.d.ts文件
```
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "index"
    | "profile"   // 自己手动加上的
  >;

  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "profile"    // 自己手动加上的
    | "index"  
  >;
```

3. 重启项目时， elegant-router.d.ts 里面的配置会被覆盖
<img width="1300" alt="image" src="https://github.com/soybeanjs/elegant-router/assets/8500410/21522924-c8bc-4dbe-8f4a-eea51a068f26">

请问怎么才能不被覆盖？

**Comment by honghuangdc** [comment]
在路由插件注册的地方修改 customRoutes 就行，然后重新启动项目，类型文件不用去手动变更，都是自动生成的

**Comment by zuihou** [comment]
> 在路由插件注册的地方修改 customRoutes 就行，然后重新启动项目，类型文件不用去手动变更，都是自动生成的

你说的是这个地方吗？

![image](https://github.com/soybeanjs/elegant-router/assets/8500410/ab5e0e17-1c3d-4b37-81f9-12f4c3d2f3b2)


只改这里，重启项目不会自动生成 CustomRouteKey

**Comment by zuihou** [comment]
可能是因为我在views/_builtin 下面创建了  profile/index.vue ，导致的没有自动 CustomRouteKey 。

我将profile/index.vue 移动到 views/common 目录下后， CustomRouteKey 自动生成了，但 views 没有生成 profile 的配置
```
# build/plugins/router.ts 中配置如下
pageExcludePatterns: ['**/components/**', '**/common/**', '**/demo/**'],
```
router/elegant/imports.ts 中没有生成  views.profile
<img width="1259" alt="image" src="https://github.com/soybeanjs/elegant-router/assets/8500410/9aba6bad-2985-4d42-bf4c-fc0aae7753b9">

导致，在routes/index.ts中无法引用  ` component: 'layout.base$view.profile', `

<img width="1120" alt="image" src="https://github.com/soybeanjs/elegant-router/assets/8500410/ba06a79a-cf9e-4982-985a-d1d6ae22789d">

**Comment by honghuangdc** [comment]
看一下这里关于自定义路由的介绍
https://docs.soybeanjs.cn/zh/guide/router/structure.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B7%AF%E7%94%B1

**Comment by zuihou** [comment]
看了的，你给的示例里面，这里的 component ,是不是要在views里面手动编写 ？


<img width="1071" alt="image" src="https://github.com/soybeanjs/elegant-router/assets/8500410/0ed2b638-afa5-4a28-80d5-a2aba67f2859">

**Comment by honghuangdc** [comment]
复用已有的路由component，已有的例如403，这个不是自定义路由

**Comment by zuihou** [comment]
> 复用已有的路由component，已有的例如403，这个不是自定义路由

比如，这里希望实现 ： /two-level ，访问页面 /views/two-level/aaa/bbb/index.vue， 要怎么配置？

<img width="1071" alt="image" src="https://github.com/soybeanjs/elegant-router/assets/8500410/0ed2b638-afa5-4a28-80d5-a2aba67f2859">

**Comment by honghuangdc** [comment]
用redirect属性去实现，具体参考vue-router

**Comment by zuihou** [comment]
> 用redirect属性去实现，具体参考vue-router

意思是， 先创建 `/views/two-level/aaa/bbb/index.vue` 文件夹，重启系统重新生成路由， 然后在customRoutes中重定向过去？

**Comment by honghuangdc** [comment]
我的建议是仔细去看文档，多看几遍

**Comment by zuihou** [comment]
不是我没看文档，是文档看不懂， 看了也解决不了这个问题 😂

**Comment by honghuangdc** [comment]
加群沟通
