### ISSUE TITLE
您好我有一个pnpm monorepo管理的项目，packages下面有两个文件夹一个 h5一个pc,我该如何使用elegant-router呢？

### ISSUE THREAD

**Issue by yyqxjwxy** [soybeanjs/elegant-router#31]
我是想这两个子项目都可以使用elegant-router，是把插件安装到项目根目录下，还是在packages下的子目录安装呢，如果在子目录安装的话如何陪配置才能使用呢

**Comment by honghuangdc** [comment]
两个项目分别安装

**Comment by yyqxjwxy** [comment]
> 两个项目分别安装

![image](https://github.com/user-attachments/assets/b32eeb24-00f3-486d-9b31-cfc1cf405ccd)
您好，我在项目的里的 pakages 里查看安装包的位置貌似还是在根目录下，导致插件在子项目没生效是为什么呢
