### ISSUE TITLE
import.ts 文件报错

### ISSUE THREAD

**Issue by yyqxjwxy** [soybeanjs/elegant-router#36]
当把 index.vue 页面改成[id].vue 时会自动触发 import.ts 生成如下代码
` "business-risk_simplified-cancellation-detail": () => import("~/src/views/business-risk/simplified-cancellation-detail/[id].vue),
  "business-risk_simplified-cancellation": () => import("@/views/business-risk/simplified-cancellation/index.vue"),`
无法把business-risk_simplified-cancellation": () => import("@/views/business-risk/simplified-cancellation/index.vue")删除掉导致文件报错

**Comment by honghuangdc** [comment]
怎么路径路面还有 这个符号`~`

**Comment by honghuangdc** [comment]
给个具体的复现步骤
