### ISSUE TITLE
给 route.ts 文件的 meta 信息设置 keepAlive:true ，页面无缓存效果

### ISSUE THREAD

**Issue by yyqxjwxy** [soybeanjs/elegant-router#37]
`  {
        name: 'business-situation_trademark-info',
        path: '/business-situation/trademark-info',
        component: 'view.business-situation_trademark-info',
        meta: {
          title: '商标',
          keepAlive: true
        }
      },
`
如上代码当前页面并没有缓存，还需要其他配置吗或者执行其他操作吗

**Comment by honghuangdc** [comment]
不用，这样就可以了

**Comment by yyqxjwxy** [comment]
> 你的页面代码正常用 script setup 方式去写，然后不要用 defineOptions 写页面的name，这个插件会自动注入

我就是script setup 的方式，也没有定义页面的defineOptions，但确实是不起效果

**Comment by honghuangdc** [comment]
你怎么验证的

**Comment by honghuangdc** [comment]
你是不是用的后端的路由数据

**Comment by yyqxjwxy** [comment]
> 你怎么验证的

![image](https://github.com/user-attachments/assets/d4033539-bd7d-40f1-bf62-31304219ded7)
您看下这是我页面的头部代码没有用defineOptions ，使用script setup的方式

**Comment by honghuangdc** [comment]
在群里沟通

**Comment by yyqxjwxy** [comment]
> 在群里沟通

还没有加群，这个页面引入了一个组件这个组件使用defineOptions 定义了组件名称，和这个有关系吗
![Code 2024-11-05 14 52 35](https://github.com/user-attachments/assets/27737b4a-e2bc-49e5-8963-7660e94d52f8)
