### ISSUE TITLE
您好，我从 0.2.6 升级到 0.3.1 项目无法启动

### ISSUE THREAD

**Issue by yyqxjwxy** [soybeanjs/elegant-router#4]
![WechatIMG278](https://github.com/soybeanjs/elegant-router/assets/17972392/5dfa76e2-2b1e-4f02-8a23-484e2a0efb3f)
项目启动时出现了上图的错误，有什么办法可以解决吗

**Comment by yyqxjwxy** [comment]
目前看到一级路由都会报错

**Comment by honghuangdc** [comment]
你看一下项目里面的packages/example项目的启动情况

**Comment by honghuangdc** [comment]
试试你把原有的路由数据文件复制一份备份，然后删掉，让插件重新生成

**Comment by yyqxjwxy** [comment]
> 试试你把原有的路由数据文件elegant/routes复制一份备份，然后删掉，让插件重新生成

您好，找到了原因，是因为生成的路由结构变化了，参照 demo 修改成功了，多谢
