### ISSUE TITLE
您好，我在我的项目里eslint.config.js配置了忽略指定的文件，为什么这个文件还是会被 eslint 格式化，点击保存的时候

### ISSUE THREAD

**Issue by yyqxjwxy** [soybeanjs/elegant-router#5]
![image](https://github.com/soybeanjs/elegant-router/assets/17972392/05f78401-76ae-4315-b0e1-0db86cef6125)

**Comment by honghuangdc** [comment]
你用的是 antfu 的 eslint-config, 请在对应仓库这里提问题 [eslint-config](https://github.com/antfu/eslint-config)

**Comment by honghuangdc** [comment]
elegant下面的文件开头都有以下的代码，不会被格式化
/* eslint-disable */
/* prettier-ignore */
